<?php

namespace HANDS\Brandedsms\Model\Config\Source;

use Magento\Framework\App\ObjectManager;

class Country implements \Magento\Framework\Option\ArrayInterface
{
	
    /**
     * @return array
     */
    public function toOptionArray()
    {
        return array(
						
						array ( 'label' => 'India (भारत)', 'value' => '91') , 
						array ( 'label' => 'Afghanistan (‫افغانستان‬‎)', 'value' => '93') , 
						array ( 'label' => 'Albania (Shqipëri)', 'value' => '355') , 
						array ( 'label' => 'Algeria (‫الجزائر‬‎)', 'value' => '213') , 
						array ( 'label' => 'American Samoa', 'value' => '1684') , 
						array ( 'label' => 'Andorra', 'value' => '376') , 
						array ( 'label' => 'Angola', 'value' => '244') , 
						array ( 'label' => 'Anguilla', 'value' => '1264') , 
						array ( 'label' => 'Antigua and Barbuda', 'value' => '1268') , 
						array ( 'label' => 'Argentina', 'value' => '54') , 
						array ( 'label' => 'Armenia (Հայաստան)', 'value' => '374') , 
						array ( 'label' => 'Aruba', 'value' => '297') , 
						array ( 'label' => 'Australia', 'value' => '61') , 
						array ( 'label' => 'Austria (Österreich)', 'value' => '43') , 
						array ( 'label' => 'Azerbaijan (Azərbaycan)', 'value' => '994') , 
						array ( 'label' => 'Bahamas', 'value' => '1242') , 
						array ( 'label' => 'Bahrain (‫البحرين‬‎)', 'value' => '973') , 
						array ( 'label' => 'Bangladesh (বাংলাদেশ)', 'value' => '880') , 
						array ( 'label' => 'Barbados', 'value' => '1246') , 
						array ( 'label' => 'Belarus (Беларусь)', 'value' => '375') , 
						array ( 'label' => 'Belgium (België)', 'value' => '32') , 
						array ( 'label' => 'Belize', 'value' => '501') , 
						array ( 'label' => 'Benin (Bénin)', 'value' => '229') , 
						array ( 'label' => 'Bermuda', 'value' => '1441') , 
						array ( 'label' => 'Bhutan (འབྲུག)', 'value' => '975') , 
						array ( 'label' => 'Bolivia', 'value' => '591') , 
						array ( 'label' => 'Bosnia and Herzegovina (Босна и Херцеговина)', 'value' => '387') , 
						array ( 'label' => 'Botswana', 'value' => '267') , 
						array ( 'label' => 'Brazil (Brasil)', 'value' => '55') , 
						array ( 'label' => 'British Indian Ocean Territory', 'value' => '246') , 
						array ( 'label' => 'British Virgin Islands', 'value' => '1284') , 
						array ( 'label' => 'Brunei', 'value' => '673') , 
						array ( 'label' => 'Bulgaria (България)', 'value' => '359') , 
						array ( 'label' => 'Burkina Faso', 'value' => '226') , 
						array ( 'label' => 'Burundi (Uburundi)', 'value' => '257') , 
						array ( 'label' => 'Cambodia (កម្ពុជា)', 'value' => '855') , 
						array ( 'label' => 'Cameroon (Cameroun)', 'value' => '237') , 
						array ( 'label' => 'Canada', 'value' => '1') , 
						array ( 'label' => 'Cape Verde (Kabu Verdi)', 'value' => '238') , 
						array ( 'label' => 'Caribbean Netherlands', 'value' => '599') , 
						array ( 'label' => 'Cayman Islands', 'value' => '1345') , 
						array ( 'label' => 'Central African Republic (République centrafricaine)', 'value' => '236') , 
						array ( 'label' => 'Chad (Tchad)', 'value' => '235') , 
						array ( 'label' => 'Chile', 'value' => '56') , 
						array ( 'label' => 'China (中国)', 'value' => '86') , 
						array ( 'label' => 'Christmas Island', 'value' => '61') , 
						array ( 'label' => 'Cocos (Keeling) Islands', 'value' => '61') , 
						array ( 'label' => 'Colombia', 'value' => '57') , 
						array ( 'label' => 'Comoros (‫جزر القمر‬‎)', 'value' => '269') , 
						array ( 'label' => 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)', 'value' => '243') , 
						array ( 'label' => 'Congo (Republic) (Congo-Brazzaville)', 'value' => '242') , 
						array ( 'label' => 'Cook Islands', 'value' => '682') , 
						array ( 'label' => 'Costa Rica', 'value' => '506') , 
						array ( 'label' => 'Côte d’Ivoire', 'value' => '225') , 
						array ( 'label' => 'Croatia (Hrvatska)', 'value' => '385') , 
						array ( 'label' => 'Cuba', 'value' => '53') , 
						array ( 'label' => 'Curaçao', 'value' => '599') , 
						array ( 'label' => 'Cyprus (Κύπρος)', 'value' => '357') , 
						array ( 'label' => 'Czech Republic (Česká republika)', 'value' => '420') , 
						array ( 'label' => 'Denmark (Danmark)', 'value' => '45') , 
						array ( 'label' => 'Djibouti', 'value' => '253') , 
						array ( 'label' => 'Dominica', 'value' => '1767') , 
						array ( 'label' => 'Dominican Republic (República Dominicana)', 'value' => '1') , 
						array ( 'label' => 'Ecuador', 'value' => '593') , 
						array ( 'label' => 'Egypt (‫مصر‬‎)', 'value' => '20') , 
						array ( 'label' => 'El Salvador', 'value' => '503') , 
						array ( 'label' => 'Equatorial Guinea (Guinea Ecuatorial)', 'value' => '240') , 
						array ( 'label' => 'Eritrea', 'value' => '291') , 
						array ( 'label' => 'Estonia (Eesti)', 'value' => '372') , 
						array ( 'label' => 'Ethiopia', 'value' => '251') , 
						array ( 'label' => 'Falkland Islands (Islas Malvinas)', 'value' => '500') , 
						array ( 'label' => 'Faroe Islands (Føroyar)', 'value' => '298') , 
						array ( 'label' => 'Fiji', 'value' => '679') , 
						array ( 'label' => 'Finland (Suomi)', 'value' => '358') , 
						array ( 'label' => 'France', 'value' => '33') , 
						array ( 'label' => 'French Guiana (Guyane française)', 'value' => '594') , 
						array ( 'label' => 'French Polynesia (Polynésie française)', 'value' => '689') , 
						array ( 'label' => 'Gabon', 'value' => '241') , 
						array ( 'label' => 'Gambia', 'value' => '220') , 
						array ( 'label' => 'Georgia (საქართველო)', 'value' => '995') , 
						array ( 'label' => 'Germany (Deutschland)', 'value' => '49') , 
						array ( 'label' => 'Ghana (Gaana)', 'value' => '233') , 
						array ( 'label' => 'Gibraltar', 'value' => '350') , 
						array ( 'label' => 'Greece (Ελλάδα)', 'value' => '30') , 
						array ( 'label' => 'Greenland (Kalaallit Nunaat)', 'value' => '299') , 
						array ( 'label' => 'Grenada', 'value' => '1473') , 
						array ( 'label' => 'Guadeloupe', 'value' => '590') , 
						array ( 'label' => 'Guam', 'value' => '1671') , 
						array ( 'label' => 'Guatemala', 'value' => '502') , 
						array ( 'label' => 'Guernsey', 'value' => '44') , 
						array ( 'label' => 'Guinea (Guinée)', 'value' => '224') , 
						array ( 'label' => 'Guinea-Bissau (Guiné Bissau)', 'value' => '245') , 
						array ( 'label' => 'Guyana', 'value' => '592') , 
						array ( 'label' => 'Haiti', 'value' => '509') , 
						array ( 'label' => 'Honduras', 'value' => '504') , 
						array ( 'label' => 'Hong Kong (香港)', 'value' => '852') , 
						array ( 'label' => 'Hungary (Magyarország)', 'value' => '36') , 
						array ( 'label' => 'Iceland (Ísland)', 'value' => '354') , 
						array ( 'label' => 'Indonesia', 'value' => '62') , 
						array ( 'label' => 'Iran (‫ایران‬‎)', 'value' => '98') , 
						array ( 'label' => 'Iraq (‫العراق‬‎)', 'value' => '964') , 
						array ( 'label' => 'Ireland', 'value' => '353') , 
						array ( 'label' => 'Isle of Man', 'value' => '44') , 
						array ( 'label' => 'Israel (‫ישראל‬‎)', 'value' => '972') , 
						array ( 'label' => 'Italy (Italia)', 'value' => '39') , 
						array ( 'label' => 'Jamaica', 'value' => '1876') , 
						array ( 'label' => 'Japan (日本)', 'value' => '81') , 
						array ( 'label' => 'Jersey', 'value' => '44') , 
						array ( 'label' => 'Jordan (‫الأردن‬‎)', 'value' => '962') , 
						array ( 'label' => 'Kazakhstan (Казахстан)', 'value' => '7') , 
						array ( 'label' => 'Kenya', 'value' => '254') , 
						array ( 'label' => 'Kiribati', 'value' => '686') , 
						array ( 'label' => 'Kosovo', 'value' => '383') , 
						array ( 'label' => 'Kuwait (‫الكويت‬‎)', 'value' => '965') , 
						array ( 'label' => 'Kyrgyzstan (Кыргызстан)', 'value' => '996') , 
						array ( 'label' => 'Laos (ລາວ)', 'value' => '856') , 
						array ( 'label' => 'Latvia (Latvija)', 'value' => '371') , 
						array ( 'label' => 'Lebanon (‫لبنان‬‎)', 'value' => '961') , 
						array ( 'label' => 'Lesotho', 'value' => '266') , 
						array ( 'label' => 'Liberia', 'value' => '231') , 
						array ( 'label' => 'Libya (‫ليبيا‬‎)', 'value' => '218') , 
						array ( 'label' => 'Liechtenstein', 'value' => '423') , 
						array ( 'label' => 'Lithuania (Lietuva)', 'value' => '370') , 
						array ( 'label' => 'Luxembourg', 'value' => '352') , 
						array ( 'label' => 'Macau (澳門)', 'value' => '853') , 
						array ( 'label' => 'Macedonia (FYROM) (Македонија)', 'value' => '389') , 
						array ( 'label' => 'Madagascar (Madagasikara)', 'value' => '261') , 
						array ( 'label' => 'Malawi', 'value' => '265') , 
						array ( 'label' => 'Malaysia', 'value' => '60') , 
						array ( 'label' => 'Maldives', 'value' => '960') , 
						array ( 'label' => 'Mali', 'value' => '223') , 
						array ( 'label' => 'Malta', 'value' => '356') , 
						array ( 'label' => 'Marshall Islands', 'value' => '692') , 
						array ( 'label' => 'Martinique', 'value' => '596') , 
						array ( 'label' => 'Mauritania (‫موريتانيا‬‎)', 'value' => '222') , 
						array ( 'label' => 'Mauritius (Moris)', 'value' => '230') , 
						array ( 'label' => 'Mayotte', 'value' => '262') , 
						array ( 'label' => 'Mexico (México)', 'value' => '52') , 
						array ( 'label' => 'Micronesia', 'value' => '691') , 
						array ( 'label' => 'Moldova (Republica Moldova)', 'value' => '373') , 
						array ( 'label' => 'Monaco', 'value' => '377') , 
						array ( 'label' => 'Mongolia (Монгол)', 'value' => '976') , 
						array ( 'label' => 'Montenegro (Crna Gora)', 'value' => '382') , 
						array ( 'label' => 'Montserrat', 'value' => '1664') , 
						array ( 'label' => 'Morocco (‫المغرب‬‎)', 'value' => '212') , 
						array ( 'label' => 'Mozambique (Moçambique)', 'value' => '258') , 
						array ( 'label' => 'Myanmar (Burma) (မြန်မာ)', 'value' => '95') , 
						array ( 'label' => 'Namibia (Namibië)', 'value' => '264') , 
						array ( 'label' => 'Nauru', 'value' => '674') , 
						array ( 'label' => 'Nepal (नेपाल)', 'value' => '977') , 
						array ( 'label' => 'Netherlands (Nederland)', 'value' => '31') , 
						array ( 'label' => 'New Caledonia (Nouvelle-Calédonie)', 'value' => '687') , 
						array ( 'label' => 'New Zealand', 'value' => '64') , 
						array ( 'label' => 'Nicaragua', 'value' => '505') , 
						array ( 'label' => 'Niger (Nijar)', 'value' => '227') , 
						array ( 'label' => 'Nigeria', 'value' => '234') , 
						array ( 'label' => 'Niue', 'value' => '683') , 
						array ( 'label' => 'Norfolk Island', 'value' => '672') , 
						array ( 'label' => 'North Korea (조선 민주주의 인민 공화국)', 'value' => '850') , 
						array ( 'label' => 'Northern Mariana Islands', 'value' => '1670') , 
						array ( 'label' => 'Norway (Norge)', 'value' => '47') , 
						array ( 'label' => 'Oman (‫عُمان‬‎)', 'value' => '968') , 
						array ( 'label' => 'Pakistan (‫پاکستان‬‎)', 'value' => '92') , 
						array ( 'label' => 'Palau', 'value' => '680') , 
						array ( 'label' => 'Palestine (‫فلسطين‬‎)', 'value' => '970') , 
						array ( 'label' => 'Panama (Panamá)', 'value' => '507') , 
						array ( 'label' => 'Papua New Guinea', 'value' => '675') , 
						array ( 'label' => 'Paraguay', 'value' => '595') , 
						array ( 'label' => 'Peru (Perú)', 'value' => '51') , 
						array ( 'label' => 'Philippines', 'value' => '63') , 
						array ( 'label' => 'Poland (Polska)', 'value' => '48') , 
						array ( 'label' => 'Portugal', 'value' => '351') , 
						array ( 'label' => 'Puerto Rico', 'value' => '1') , 
						array ( 'label' => 'Qatar (‫قطر‬‎)', 'value' => '974') , 
						array ( 'label' => 'Réunion (La Réunion)', 'value' => '262') , 
						array ( 'label' => 'Romania (România)', 'value' => '40') , 
						array ( 'label' => 'Russia (Россия)', 'value' => '7') , 
						array ( 'label' => 'Rwanda', 'value' => '250') , 
						array ( 'label' => 'Saint Barthélemy', 'value' => '590') , 
						array ( 'label' => 'Saint Helena', 'value' => '290') , 
						array ( 'label' => 'Saint Kitts and Nevis', 'value' => '1869') , 
						array ( 'label' => 'Saint Lucia', 'value' => '1758') , 
						array ( 'label' => 'Saint Martin (Saint-Martin (partie française))', 'value' => '590') , 
						array ( 'label' => 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)', 'value' => '508') , 
						array ( 'label' => 'Saint Vincent and the Grenadines', 'value' => '1784') , 
						array ( 'label' => 'Samoa', 'value' => '685') , 
						array ( 'label' => 'San Marino', 'value' => '378') , 
						array ( 'label' => 'São Tomé and Príncipe (São Tomé e Príncipe)', 'value' => '239') , 
						array ( 'label' => 'Saudi Arabia (‫المملكة العربية السعودية‬‎)', 'value' => '966') , 
						array ( 'label' => 'Senegal (Sénégal)', 'value' => '221') , 
						array ( 'label' => 'Serbia (Србија)', 'value' => '381') , 
						array ( 'label' => 'Seychelles', 'value' => '248') , 
						array ( 'label' => 'Sierra Leone', 'value' => '232') , 
						array ( 'label' => 'Singapore', 'value' => '65') , 
						array ( 'label' => 'Sint Maarten', 'value' => '1721') , 
						array ( 'label' => 'Slovakia (Slovensko)', 'value' => '421') , 
						array ( 'label' => 'Slovenia (Slovenija)', 'value' => '386') , 
						array ( 'label' => 'Solomon Islands', 'value' => '677') , 
						array ( 'label' => 'Somalia (Soomaaliya)', 'value' => '252') , 
						array ( 'label' => 'South Africa', 'value' => '27') , 
						array ( 'label' => 'South Korea (대한민국)', 'value' => '82') , 
						array ( 'label' => 'South Sudan (‫جنوب السودان‬‎)', 'value' => '211') , 
						array ( 'label' => 'Spain (España)', 'value' => '34') , 
						array ( 'label' => 'Sri Lanka (ශ්‍රී ලංකාව)', 'value' => '94') , 
						array ( 'label' => 'Sudan (‫السودان‬‎)', 'value' => '249') , 
						array ( 'label' => 'Surilabel', 'value' => '597') , 
						array ( 'label' => 'Svalbard and Jan Mayen', 'value' => '47') , 
						array ( 'label' => 'Swaziland', 'value' => '268') , 
						array ( 'label' => 'Sweden (Sverige)', 'value' => '46') , 
						array ( 'label' => 'Switzerland (Schweiz)', 'value' => '41') , 
						array ( 'label' => 'Syria (‫سوريا‬‎)', 'value' => '963') , 
						array ( 'label' => 'Taiwan (台灣)', 'value' => '886') , 
						array ( 'label' => 'Tajikistan', 'value' => '992') , 
						array ( 'label' => 'Tanzania', 'value' => '255') , 
						array ( 'label' => 'Thailand (ไทย)', 'value' => '66') , 
						array ( 'label' => 'Timor-Leste', 'value' => '670') , 
						array ( 'label' => 'Togo', 'value' => '228') , 
						array ( 'label' => 'Tokelau', 'value' => '690') , 
						array ( 'label' => 'Tonga', 'value' => '676') , 
						array ( 'label' => 'Trinidad and Tobago', 'value' => '1868') , 
						array ( 'label' => 'Tunisia (‫تونس‬‎)', 'value' => '216') , 
						array ( 'label' => 'Turkey (Türkiye)', 'value' => '90') , 
						array ( 'label' => 'Turkmenistan', 'value' => '993') , 
						array ( 'label' => 'Turks and Caicos Islands', 'value' => '1649') , 
						array ( 'label' => 'Tuvalu', 'value' => '688') , 
						array ( 'label' => 'U.S. Virgin Islands', 'value' => '1340') , 
						array ( 'label' => 'Uganda', 'value' => '256') , 
						array ( 'label' => 'Ukraine (Україна)', 'value' => '380') , 
						array ( 'label' => 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)', 'value' => '971') , 
						array ( 'label' => 'United Kingdom', 'value' => '44') , 
						array ( 'label' => 'United States', 'value' => '1') , 
						array ( 'label' => 'Uruguay', 'value' => '598') , 
						array ( 'label' => 'Uzbekistan (Oʻzbekiston)', 'value' => '998') , 
						array ( 'label' => 'Vanuatu', 'value' => '678') , 
						array ( 'label' => 'Vatican City (Città del Vaticano)', 'value' => '39') , 
						array ( 'label' => 'Venezuela', 'value' => '58') , 
						array ( 'label' => 'Vietnam (Việt Nam)', 'value' => '84') , 
						array ( 'label' => 'Wallis and Futuna (Wallis-et-Futuna)', 'value' => '681') , 
						array ( 'label' => 'Western Sahara (‫الصحراء الغربية‬‎)', 'value' => '212') , 
						array ( 'label' => 'Yemen (‫اليمن‬‎)', 'value' => '967') , 
						array ( 'label' => 'Zambia', 'value' => '260') , 
						array ( 'label' => 'Zimbabwe', 'value' => '263') , 
						array ( 'label' => 'Åland Islands', 'value' => '358')
					);
	}
}